version: "1.0"
targets:
  grounded_min: 0.90
inputs:
  prompts:
    - lang: en
      text: "I feel restless and worried lately."
      topic: anxiety
    - lang: en
      text: "I’ve been sad and unmotivated for weeks."
      topic: depression
execution:
  repeats: 1     # run each prompt once; raise if you want more coverage
